spring:
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: /my-db

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    security:
      oauth2:
        client:
          registration:
            google:
              # 구글에서 복사한 클라이언트 ID
              client-id: YOUR_GOOGLE_CLIENT_ID
              # 구글에서 복사한 보안 비밀번호
              client-secret: YOUR_GOOGLE_CLIENT_SECRET
              scope:
                - profile
                - email

jwt:
  secret: echorunsecretkeyforenvironmentandploggingplatform2026
  # 토큰 유효시간
  expiration-time: 604800000

springdoc:
  swagger-ui:
    # Swagger 접속 경로를 더 짧게 만들어줍니다. (기본값은 /swagger-ui/index.html)
    path: /swagger-ui.html
    # API가 만들어진 순서대로(컨트롤러에 적힌 순서대로) 화면에 정렬해줍니다.
    operations-sorter: alpha

  api-docs:
    path: /v3/api-docs
    info:
      title: "EchoRun API 명세서"
      version: "v1.0"
      description: "### 🔐 소셜 로그인 및 인증 연동 가이드\n\n1. **구글 로그인 요청 (기능 1)**\n   - 프론트엔드에서 사용자가 구글 로그인 버튼을 누르면 다음 주소로 브라우저 창을 이동(Redirect) 시켜주세요.\n   - URL: `GET http://localhost:8080/oauth2/authorization/google`\n\n2. **로그인 성공 리다이렉트 및 JWT 발급 (기능 2)**\n   - 구글 인증이 완료되면 백엔드가 프론트엔드로 다시 주소를 리다이렉트 시킵니다.\n   - 이때 주소창 파라미터에 JWT 토큰을 실어서 보냅니다.\n   - 형식: `http://localhost:3000/oauth/redirect?token=eyJhbGciOi...`\n   - 프론트엔드는 이 주소창에서 `token` 값을 파싱해서 로컬 스토리지에 저장한 뒤 사용하세요.\n\n3. **인증이 필요한 API 호출 시 주의사항**\n   - `러닝 시작`, `러닝 종료` 등 유저 정보가 필요한 모든 API는 헤더에 토큰을 담아야 합니다.\n   - Header key: `Authorization` / Value: `Bearer {발급받은_JWT_토큰}`"

gemini:
  api:
    key: "AIzaSyDuTuqVNJQyZpMasAolrideHVEzBtutiSU"