spring:
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: /my-db

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    security:
      oauth2:
        client:
          registration:
            google:
              # 구글에서 복사한 클라이언트 ID
              client-id: YOUR_GOOGLE_CLIENT_ID
              # 구글에서 복사한 보안 비밀번호
              client-secret: YOUR_GOOGLE_CLIENT_SECRET
              scope:
                - profile
                - email

jwt:
  secret: echorunsecretkeyforenvironmentandploggingplatform2026
  # 토큰 유효시간
  expiration-time: 604800000

springdoc:
  swagger-ui:
    # Swagger 접속 경로를 더 짧게 만들어줍니다. (기본값은 /swagger-ui/index.html)
    path: /swagger-ui.html
    # API가 만들어진 순서대로(컨트롤러에 적힌 순서대로) 화면에 정렬해줍니다.
    operations-sorter: alpha